require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require 'json'

podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

# Enable New Architecture consistently as per app.json
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Enable Hermes
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods', :deterministic_uuids => false

prepare_react_native_project!

target 'frontend' do
  use_expo_modules!
  config = use_native_modules!

  # Force static linking for compatibility
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,              # Hermes enabled here
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  pod 'ICBleProtocol', :path => './SDKPodspecs'
  pod 'ICBodyFatAlgorithms', :path => './SDKPodspecs'
  pod 'ICDeviceManager', :path => './SDKPodspecs'
  pod 'ICLogger', :path => './SDKPodspecs'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )
  end
end
